services:
  go_app:
    image: ghcr.io/dendanskemetode/legacyproject:latest
    expose:
      - "3000"
    environment:
      - PORT=3000
    networks:
      - backend

  nginx:
    build: ./network
    ports:
      - "80:80"
    depends_on:
      - go_app
    networks:
      - backend

networks:
  backend:
    driver: bridge
